baseURL = "https://www.hipatiya.com/"
languageCode = "en-us"
title = "Hipatiya"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

[[menu.main]]
    name = "Hizmetlerimiz"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "Hakkımızda"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Referanslar"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "İletişim"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
